---
- name: "Generate a random password: root"
  ansible.builtin.set_fact:
    first_contact_root_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
  when: first_contact_root_password_update and first_contact_root_password is none or (first_contact_root_password | default('')) == ''

- name: "Ensure correct first_contact_root_password is set: root"
  become: true
  ansible.builtin.user:
    name: "root"
    password: "{{ first_contact_root_password | password_hash('sha512', first_contact_salt) }}"
    update_password: "always"
  notify:
    - "Restart sshd service"
    - "Restart sshd service (Ubuntu 24.04)"
  when: first_contact_root_password_update

- name: "Ensure SSH is disabled for root"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
    validate: "sshd -t -f %s"
  notify:
    - "Restart sshd service"
    - "Restart sshd service (Ubuntu 24.04)"
  when: first_contact_root_ssh_disable

- name: "Ensure root user login is disabled"
  become: true
  ansible.builtin.user:
    name: "root"
    shell: "/sbin/nologin"
    state: present
  notify:
    - "Restart sshd service"
    - "Restart sshd service (Ubuntu 24.04)"
  when: first_contact_root_login_disable is true

- name: "Ensure root user login is enabled"
  become: true
  ansible.builtin.user:
    name: "root"
    shell: "/bin/bash"
    state: present
  notify:
    - "Restart sshd service"
    - "Restart sshd service (Ubuntu 24.04)"
  when: first_contact_root_login_disable is false
