---
# Second contact is for hosts that have a deploy user that is already accessable with sudo.
# If python3 is not installed then bootstrap (raw)
- name: "Test python3"
  block:
    - name: "Test python3 is installed"
      ansible.builtin.raw: "python3 --version"
      changed_when: false
  rescue:
    - name: "Set python3_not_installed fact"
      ansible.builtin.set_fact:
        python3_not_installed: true

- name: "Test python"
  when: python3_not_installed is defined
  block:
    - name: "Test python is installed"
      ansible.builtin.raw: "python --version"
      changed_when: false
  rescue:
    - name: "Set python_not_installed fact"
      ansible.builtin.set_fact:
        python_not_installed: true

- name: "Bootstrap"
  when: python3_not_installed is defined and python_not_installed is defined
  block:
    - name: "Bootstrap"
      ansible.builtin.import_role:
        name: robertdebock.bootstrap

- name: "Gathering facts"
  ansible.builtin.setup:
  when: ansible_facts|default({}) == {}

# Useful if deploy user has logged in using a different SSH key to first_contact_ssh_public_key_file
- name: "Configure ansible deploy user: {{ first_contact_deploy_user }}"
  block:
    - name: "SSH key check"
      ansible.builtin.include_tasks: ssh_key_check.yml

    - name: "Ensure SSH public key is on host: {{ first_contact_deploy_user }}"
      ansible.posix.authorized_key:
        user: "{{ first_contact_deploy_user }}"
        state: present
        key: "{{ lookup('file', '{{ first_contact_ssh_public_key_file }}') }}"
      register: ssh_key_copied
      when: not ssh_public_key_file_stat.stat.exists

    - name: "Ensure correct first_contact_deploy_password is set: {{ first_contact_deploy_user }}"
      become: true
      ansible.builtin.user:
        name: "{{ first_contact_deploy_user }}"
        password: "{{ first_contact_deploy_password | password_hash('sha512') }}"
        update_password: "{{ first_contact_deploy_password_update }}"
      when: first_contact_deploy_password_update == "always"

- name: "Bootstrap"
  ansible.builtin.import_role:
    name: robertdebock.bootstrap
  when: ssh_key_copied is defined and ssh_key_copied.changed

- name: "Core dependencies"
  ansible.builtin.import_role:
    name: robertdebock.core_dependencies
