---
- name: "Test connection"
  block:
    - name: "Test connection for ansible deploy user: {{ deploy_user }}"
      remote_user: "{{ deploy_user }}"
      ansible.builtin.wait_for_connection:
        timeout: "{{ connection_timeout }}"

    - name: "Test sudo access for ansible deploy: {{ deploy_user }}"
      become: true
      ansible.builtin.raw: sudo --version
      changed_when: false

  rescue:
    - name: "First contact"
      ansible.builtin.import_tasks: first_contact.yml

    - name: "Set fact first_contact_complete"
      ansible.builtin.set_fact:
        first_contact_complete: true

- name: "Test Python"
  ansible.builtin.import_tasks: python.yml
