---
- name: "Test connection"
  block:
    - name: "Test connection for ansible deploy user: {{ first_contact_deploy_user }}"
      remote_user: "{{ first_contact_deploy_user }}"
      ansible.builtin.wait_for_connection:
        timeout: "{{ first_contact_connection_timeout }}"

    - name: "Test sudo access for ansible deploy: {{ first_contact_deploy_user }}"
      become: true
      ansible.builtin.raw: sudo --version
      changed_when: false

    - name: "Second contact"
      ansible.builtin.include_tasks: second_contact.yml

  rescue:
    - name: "First contact"
      ansible.builtin.include_tasks: first_contact.yml

- name: "Test first_contact_deploy_user is accessible"
  block:
    - name: "Test connection for ansible deploy user: {{ first_contact_deploy_user }}"
      remote_user: "{{ first_contact_deploy_user }}"
      ansible.builtin.wait_for_connection:
        timeout: "{{ first_contact_connection_timeout }}"

    - name: "Test sudo access for ansible deploy: {{ first_contact_deploy_user }}"
      become: true
      ansible.builtin.raw: sudo --version
      changed_when: false

    - name: "Root user"
      ansible.builtin.import_tasks: root_user.yml
