---
- name: "Prepare"
  hosts: all
  gather_facts: false

  tasks:
    - name: "Create home directory"
      delegate_to: localhost
      ansible.builtin.file:
        path: "${HOME}"
        state: directory
        mode: 0700

    - name: "Create .ssh directory"
      delegate_to: localhost
      ansible.builtin.file:
        path: "${HOME}/.ssh"
        state: directory
        mode: 0700

    - name: "Create known_hosts file"
      delegate_to: localhost
      ansible.builtin.file:
        path: "${HOME}/.ssh/known_hosts"
        state: touch
        mode: 0600

    - name: "Generate ed25519 key"
      delegate_to: localhost
      community.crypto.openssh_keypair:
        path: "${HOME}/.ssh/id_ed25519"
        type: ed25519
        size: 4096
        force: true
