---
- name: prepare
  hosts: all
  gather_facts: false

  roles:
    - role: dgibbs64.generate_ssh_keys

  pre_tasks:
    - name: create /root/.ssh/known_hosts
      file:
        path: /root/.ssh/known_hosts
        state: touch
        mode: 0600
      delegate_to: 127.0.0.1
