---
- name: prepare
  hosts: all
  gather_facts: false
  become: true

  pre_tasks:
    - name: "Create root home directory"
      delegate_to: localhost
      ansible.builtin.file:
        path: "${HOME}"
        state: directory
        mode: 0700

    - name: "Create root .ssh directory"
      delegate_to: localhost
      ansible.builtin.file:
        path: "${HOME}/.ssh"
        state: directory
        mode: 0700

    - name: "Create known_hosts file"
      delegate_to: localhost
      ansible.builtin.file:
        path: "${HOME}/.ssh/known_hosts"
        state: touch
        mode: 0600
