---
- name: "Verify"
  hosts: all

  tasks:
    - name: "Check if connection still works"
      ansible.builtin.ping:

    - name: "Set deploy_user to current user"
      become: false
      ansible.builtin.command: whoami
      register: whoami
      changed_when: false
      delegate_to: localhost

    - name: "Set deploy_user fact"
      ansible.builtin.set_fact:
        deploy_user: "{{ whoami.stdout }}"

    - name: "Display deploy_user"
      ansible.builtin.debug:
        msg: "deploy_user: {{ deploy_user }}"

    - name: "Test connection for ansible deploy user: {{ deploy_user }}"
      remote_user: "{{ deploy_user }}"
      ansible.builtin.wait_for_connection:
