---
- name: "Verify"
  hosts: all
  gather_facts: false
  tasks:
    - name: "Check if connection still works"
      ansible.builtin.ping:

    - name: "Set first_contact_deploy_user to current user"
      become: false
      ansible.builtin.command: whoami
      register: first_contact_whoami
      changed_when: false
      delegate_to: localhost

    - name: "Set first_contact_deploy_user fact"
      ansible.builtin.set_fact:
        first_contact_deploy_user: "{{ first_contact_whoami.stdout }}"

    - name: "Display first_contact_deploy_user"
      ansible.builtin.debug:
        msg: "first_contact_deploy_user: {{ first_contact_deploy_user }}"

    - name: "Test connection for ansible deploy user: {{ first_contact_deploy_user }}"
      remote_user: "{{ first_contact_deploy_user }}"
      ansible.builtin.wait_for_connection:
