---
name: Ansible Molecule
on:
  push:
  pull_request:
  schedule:
    - cron: "47 22 24 * *"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          #- image: "rockylinux"
          #  tag: "latest"
          #- image: "centos"
          #  tag: "7"
          #- image: "debian"
          #  tag: "latest"
          #- image: "debian"
          #  tag: "bookworm"
          #- image: "fedora"
          #  tag: "latest"
          #- image: "fedora"
          #  tag: "rawhide"
          - image: "ubuntu"
            tag: "latest"
          #- image: "ubuntu"
          #  tag: "focal"
          #- image: "ubuntu"
          #  tag: "bionic"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@4.0.9
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
